# Generated by Django 5.1.4 on 2025-04-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipe'),
        ),
    ]
